name: datawedgeflutter
description: Accessing DataWedge from a Flutter app

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3
  get: ^4.6.5
  buttons_tabbar: ^1.3.6
  path_provider: ^2.0.11
  pdf: ^3.8.1
  open_file: ^3.2.1
  intl: ^0.17.0
  share_extend: ^2.0.0
  cloud_firestore: ^3.3.0
  firebase_auth: ^3.4.2
  get_storage: ^2.0.3
  sizer: ^2.0.15
  mask_text_input_formatter: ^2.3.0
  timelines: ^0.1.0
  cached_network_image: ^3.2.1
  change_app_package_name: ^1.1.0
  bottom_nav_layout: ^3.0.9
  flutter_offline: ^2.1.0
  uuid: ^3.0.6
  barcode_widgets: ^2.0.0
  scrollable_positioned_list: ^0.3.5
  awesome_dialog: ^3.0.2
  photo_view: ^0.14.0
  customizable_counter: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/background/
    - assets/images/icons/
    - assets/images/icons/flags/
    - assets/images/icons/tabs/
    - assets/images/logos/

  fonts:
    - family: Mirza
      fonts:
        - asset: fonts/Mirza-Regular.ttf
        - asset: fonts/Hacentunisia.ttf